services:
  telegram-bots:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY